//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoThuXiGon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoThuXiGon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _22237184_899105450241975_1993755261_n {
            get {
                object obj = ResourceManager.GetObject("22237184_899105450241975_1993755261_n", resourceCulture);
=======
        internal static System.Drawing.Bitmap _22236510_899105800241940_285828348_n {
            get {
                object obj = ResourceManager.GetObject("22236510_899105800241940_285828348_n", resourceCulture);
>>>>>>> b73b8364da1e49c22f209ff8b7393af286904964
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _22237364_899104636908723_1058093624_n {
            get {
                object obj = ResourceManager.GetObject("22237364_899104636908723_1058093624_n", resourceCulture);
=======
        internal static System.Drawing.Bitmap _22237140_899106180241902_830899415_n {
            get {
                object obj = ResourceManager.GetObject("22237140_899106180241902_830899415_n", resourceCulture);
>>>>>>> b73b8364da1e49c22f209ff8b7393af286904964
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _22264857_899105310241989_384452708_n {
            get {
                object obj = ResourceManager.GetObject("22264857_899105310241989_384452708_n", resourceCulture);
=======
        internal static System.Drawing.Bitmap _22237346_899106123575241_282595326_n {
            get {
                object obj = ResourceManager.GetObject("22237346_899106123575241_282595326_n", resourceCulture);
>>>>>>> b73b8364da1e49c22f209ff8b7393af286904964
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _22278434_899104883575365_1500821187_n {
            get {
                object obj = ResourceManager.GetObject("22278434_899104883575365_1500821187_n", resourceCulture);
=======
        internal static System.Drawing.Bitmap _22278662_899105956908591_2113989847_n {
            get {
                object obj = ResourceManager.GetObject("22278662_899105956908591_2113989847_n", resourceCulture);
>>>>>>> b73b8364da1e49c22f209ff8b7393af286904964
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _22278496_899104666908720_1730919654_n {
            get {
                object obj = ResourceManager.GetObject("22278496_899104666908720_1730919654_n", resourceCulture);
=======
        internal static System.Drawing.Bitmap _22291894_899105873575266_244416957_n {
            get {
                object obj = ResourceManager.GetObject("22291894_899105873575266_244416957_n", resourceCulture);
>>>>>>> b73b8364da1e49c22f209ff8b7393af286904964
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _22291894_899105873575266_244416957_n {
            get {
                object obj = ResourceManager.GetObject("22291894_899105873575266_244416957_n", resourceCulture);
=======
        internal static System.Drawing.Bitmap _22291936_899106060241914_227507802_n {
            get {
                object obj = ResourceManager.GetObject("22291936_899106060241914_227507802_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _22291936_899106060241914_227507802_n1 {
            get {
                object obj = ResourceManager.GetObject("22291936_899106060241914_227507802_n1", resourceCulture);
>>>>>>> b73b8364da1e49c22f209ff8b7393af286904964
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
